<?php
include_once("database/db.php");

// Only Admin can access this page
if (!isset($_SESSION['Permission']) || $_SESSION['Permission'] !== '1') {
    echo "<script>alert('Access denied. Admins only.'); window.location.href='index.php';</script>";
    exit();
}
// Fetch summary data
$totalBooks = mysqli_fetch_assoc(mysqli_query($conn, "SELECT COUNT(*) AS total FROM books"))['total'];
$totalUsers = mysqli_fetch_assoc(mysqli_query($conn, "SELECT COUNT(*) AS total FROM users"))['total'];
$bannedUsers = mysqli_fetch_assoc(mysqli_query($conn, "SELECT COUNT(*) AS total FROM users WHERE Status = 'Banned'"))['total'];
$borrowedBooks = mysqli_fetch_assoc(mysqli_query($conn, "SELECT COUNT(*) AS total FROM books WHERE Status = 'Borrowed'"))['total'];
$availableBooks = mysqli_fetch_assoc(mysqli_query($conn, "SELECT COUNT(*) AS total FROM books WHERE Status = 'Available'"))['total'];

// Fetch transaction history (Borrow Report)
$transactionHistory = mysqli_query($conn, 
    "SELECT t.TransactionID, b.Title, u.FirstName, u.LastName, t.BorrowDate, t.ReturnDate
     FROM transactions t 
     JOIN books b ON t.BookID = b.BookID
     JOIN users u ON t.UserID = u.UserID
     ORDER BY t.BorrowDate DESC");
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Library Management - Reports</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
</head>
<body class="bg-light">

<div class="container mt-4">
    <h2 class="text-center">📊 Library Reports</h2>
    <p class="text-center text-muted">Generated by Admin: <?php echo $_SESSION['UserName']; ?></p>
    
    <!-- Summary Cards -->
    <div class="row text-center mt-4">
        <div class="col-md-2">
            <div class="card shadow p-3">
                <h5>Total Books</h5>
                <h3><?php echo $totalBooks; ?></h3>
            </div>
        </div>
        <div class="col-md-2">
            <div class="card shadow p-3">
                <h5>Total Users</h5>
                <h3><?php echo $totalUsers; ?></h3>
            </div>
        </div>
        <div class="col-md-2">
            <div class="card shadow p-3">
                <h5>Banned Users</h5>
                <h3 class="text-danger"><?php echo $bannedUsers; ?></h3>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card shadow p-3">
                <h5>Borrowed Books</h5>
                <h3 class="text-warning"><?php echo $borrowedBooks; ?></h3>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card shadow p-3">
                <h5>Available Books</h5>
                <h3 class="text-success"><?php echo $availableBooks; ?></h3>
            </div>
        </div>
    </div>

    <!-- Borrow Report Table -->
    <div class="card shadow p-4 mt-4">
        <h4>📘 Book Borrowing History</h4>
        <table class="table table-bordered table-striped mt-3">
            <thead class="table-dark">
                <tr>
                    <th>Transaction ID</th>
                    <th>Book Title</th>
                    <th>User</th>
                    <th>Borrow Date</th>
                    <th>Return Date</th>
                </tr>
            </thead>
            <tbody>
                <?php while ($row = mysqli_fetch_assoc($transactionHistory)) { ?>
                <tr>
                    <td><?php echo $row['TransactionID']; ?></td>
                    <td><?php echo $row['Title']; ?></td>
                    <td><?php echo $row['FirstName'] . " " . $row['LastName']; ?></td>
                    <td><?php echo $row['BorrowDate']; ?></td>
                    <td>
                        <?php 
                            if ($row['ReturnDate'] == NULL) {
                                echo "<span class='badge bg-warning'>Not Returned</span>";
                            } else {
                                echo $row['ReturnDate'];
                            }
                        ?>
                    </td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>

</body>
</html>
