<?php
include_once("database/db.php");

// Only Admin can access this page
if (!isset($_SESSION['Permission']) || $_SESSION['Permission'] !== '1') {
    echo "<script>alert('Access denied. Admins only.'); window.location.href='index.php';</script>";
    exit();
}

// Fetch summary data
$totalBooks = mysqli_fetch_assoc(mysqli_query($conn, "SELECT COUNT(*) AS total FROM books"))['total'];
$totalUsers = mysqli_fetch_assoc(mysqli_query($conn, "SELECT COUNT(*) AS total FROM users"))['total'];
$bannedUsers = mysqli_fetch_assoc(mysqli_query($conn, "SELECT COUNT(*) AS total FROM users WHERE Status = 'Banned'"))['total'];
$borrowedBooks = mysqli_fetch_assoc(mysqli_query($conn, "SELECT COUNT(*) AS total FROM transactions WHERE Status = 'APPROVE'"))['total'];
$availableBooks = mysqli_fetch_assoc(mysqli_query($conn, "SELECT COUNT(*) AS total FROM books WHERE Status = 'Available'"))['total'];
$unavailableBooks = mysqli_fetch_assoc(mysqli_query($conn, "SELECT COUNT(*) AS total FROM books WHERE Status = 'Unavailable'"))['total'];

// Fetch transaction history (Borrow Report)
$transactionHistory = mysqli_query($conn, 
    "SELECT t.TransactionID, b.Title, u.FirstName, u.LastName, t.BorrowDate, t.ReturnDate
     FROM transactions t 
     JOIN books b ON t.BookID = b.BookID
     JOIN users u ON t.UserID = u.UserID
     ORDER BY t.BorrowDate ASC");
?>

<!DOCTYPE html>
<html lang="en">
<head>
	<title>Report</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="format-detection" content="telephone=no">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="author" content="">
	<meta name="keywords" content="">
	<meta name="description" content="">

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="css/normalize.css">
	<link rel="stylesheet" type="text/css" href="icomoon/icomoon.css">
	<link rel="stylesheet" type="text/css" href="css/vendor.css">
	<link rel="stylesheet" type="text/css" href="style.css">

    <!-- <style>
        /* Disable the link visually and functionally */
        .disabled-link {
            pointer-events: none; /* Prevent clicks */
            opacity: 0.6;         /* Make it look disabled */
            cursor: not-allowed;  /* Show "not-allowed" cursor */
            text-decoration: none; /* Remove underline */
        }
    </style> -->
</head>
<body class="bg-light">

<?php include 'header.php'; ?>

<div class="container mt-4">
    <h2 class="text-center"> Library Reports</h2>
    <p class="text-center text-muted">Generated by Admin: <?php echo $_SESSION['UserName']; ?></p>

    <!-- ✅ Buttons Section -->
    <div class="d-flex justify-content-between mt-4">
        <!-- Back to Dashboard -->
        <a href="index.php" class="btn btn-secondary"> Back to Index</a>

        <!-- Export Dropdown -->
        <div class="dropdown">
            <button class="btn btn-success dropdown-toggle" type="button" id="exportDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                 Export Report
            </button>
            <ul class="dropdown-menu" aria-labelledby="exportDropdown">
                <li><a class="dropdown-item" href="export_report.php?limit=5">Export 5 Records</a></li>
                <li><a class="dropdown-item" href="export_report.php?limit=10">Export 10 Records</a></li>
                <li><a class="dropdown-item" href="export_report.php?limit=20">Export 20 Records</a></li>
                <li><a class="dropdown-item" href="export_report.php?limit=50">Export 50 Records</a></li>
                <li><a class="dropdown-item" href="export_report.php?limit=100">Export 100 Records</a></li>
            </ul>
        </div>
    </div>

    <!-- Summary Cards -->
<div class="row text-center mt-4">
    <div class="col-md-2">
        <div class="card shadow p-3">
            <h5>Total Type of Books</h5>
            <h3><?php echo $totalBooks; ?></h3>
        </div>
    </div>
    <div class="col-md-2">
        <div class="card shadow p-3">
            <h5>Total Users</h5>
            <h3><?php echo $totalUsers; ?></h3>
        </div>
    </div>
    <div class="col-md-2">
        <div class="card shadow p-3">
            <h5>Banned Users</h5>
            <h3 class="text-danger"><?php echo $bannedUsers; ?></h3>
        </div>
    </div>
    <div class="col-md-2">
        <div class="card shadow p-3">
            <h5>Borrowed Books</h5>
            <h3 class="text-warning"><?php echo $borrowedBooks; ?></h3>
        </div>
    </div>
    <div class="col-md-2">
        <div class="card shadow p-3">
            <h5>Available Books</h5>
            <h3 class="text-success"><?php echo $availableBooks; ?></h3>
        </div>
    </div>
    <div class="col-md-2">
        <div class="card shadow p-3">
            <h5>Unavailable Books</h5>
            <h3 class="text-danger"><?php echo $unavailableBooks; ?></h3>
        </div>
    </div>
</div>


    <!-- Borrow Report Table -->
    <div class="card shadow p-4 mt-4">
        <h4>📘 Book Borrowing History</h4>
        <table class="table table-bordered table-striped mt-3">
            <thead class="table-dark">
                <tr>
                    <th>Transaction ID</th>
                    <th>Book Title</th>
                    <th>User</th>
                    <th>Borrow Date</th>
                    <th>Return Date</th>
                </tr>
            </thead>
            <tbody>
                <?php while ($row = mysqli_fetch_assoc($transactionHistory)) { ?>
                <tr>
                    <td><?php echo $row['TransactionID']; ?></td>
                    <td><?php echo $row['Title']; ?></td>
                    <td><?php echo $row['FirstName'] . " " . $row['LastName']; ?></td>
                    <td><?php echo $row['BorrowDate']; ?></td>
                    <td>
                        <?php 
                            if ($row['ReturnDate'] == NULL) {
                                echo "<span class='badge bg-warning'>Not Returned</span>";
                            } else {
                                echo $row['ReturnDate'];
                            }
                        ?>
                    </td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>

<?php include 'footer.php'; ?>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
